### ISSUE TITLE
how to calculate normal map and position map from depth map

### ISSUE THREAD

**Issue by HonglinChu** [waldenlakes/PNRNet#1]
hi, thanks for your contribution, i want to know how to calculate normal map and position map from depth map

**Comment by HonglinChu** [comment]
how to know camera intrinsic for each image

**Comment by waldenlakes** [comment]
Hi, 
Thanks for your interest in our research! The supplementary material about the calculation of the normal map can be found at https://ieeexplore.ieee.org/document/9785513/media#media. 

As shown in Eq.2 in the supplementary material, we first unproject the depth map into the point cloud using the camera intrinsic K. NOTE THAT we set the FOV to 90 to calculate K for all images. Then, we estimate the normal by the plane fitting method. In addition, the position map is the XYZ of the point cloud.
